spring.application.name=futcom
server.port=${PORT:8080}

# Conexion a MySQL (Variables estándar para Railway/Spring)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Open-Meteo API
openmeteo.base-url=${OPENMETEO_BASE_URL}

# Spring Security - JWT
# Nota: Asegúrate de tener la variable JWT_SECRET en las Variables de Railway

# Evita conflicto entre Springdoc y HATEOAS
springdoc.enable-hateoas=false


# Spring Security - JWT
#jwt.secret=${JWT_SECRET}
# JwtUtil lee JWT_SECRET directamente desde la variable de entorno